=== aarepuu/bookish/schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Peruse book schema",
    "type": "object",
    "definitions": {
        "embed": {
            "type": "string",
            "pattern": "^\\|.+\\|.+\\|.+\\|.+\\|$"
        }
    },
	"required": [
        "title", "authors", "cover", "unknown", "description",
        "chapters", "revisions", "license", "sources", "references"
    ],
    "additionalProperties": false,
	"properties": {
        "title": { "type": "string" },
        "authors": {
            "type": "array",
            "items": { "type": "string" }
        },
        "cover": { "$ref": "#/definitions/embed" },
        "unknown": { "$ref": "#/definitions/embed" },
        "description": { "type": "string" },
        "chapters": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["id", "title", "image"],
                "properties": {
                    "id": { "type": "string", "pattern": "^[a-zA-Z0-9]+$"},
                    "title": { "type": "string" },
                    "image": { "$ref": "#/definitions/embed" },
                    "numbered": { "type": "boolean", "default": "True by default" },
                    "contributors": { "type": "array", "items": { "type": "string" }}
                }
            }
        },
        "revisions": {
            "type": "array",
            "items": {
                "type": "array",
                "minItems": 2,
                "maxItems": 2,
                "items": { "type": "string" }
            }
        },
        "license": { "type": "string" },
        "sources": { "type": "object", "additionalProperties": { "type": "string" } },
        "references": {
            "type": "object",
            "additionalProperties": {
                "oneOf": [
                    { "type": "string" },
                    {
                        "type": "array",
                        "maxItems": 6,
                        "items": [
                            { "type": "string" },
                            { "type": "integer"},
                            { "type": "string" },
                            { "type": "string" },
                            { "type": ["string", "null"], "format": "uri" }
                        ],
                        "additionalItems": { "type": "string"}
                    }
                ]
            }
        }
    }
}

=== aarepuu/bookish/examples/tutorial/book.json
{
	"title": "Peruse Tutorial",
	"authors": ["[Amy J. Ko|https://faculty.washington.edu/ajko/]"],
	"cover": "|cover.jpg|A photograph of Boomy the cat sleeping|Boomy is excited that you're trying Peruse!|Amy J. Ko|",
	"unknown": "|unknown.jpg|A photograph of Boomy the cat looking skeptical.|Boomy is worried that you're lost.|Amy J. Ko|",
	"description": "This is an example book, intended for presentation with the Peruse framework. Don't let it's simplicity fool you: it demonstrates all of the features of peruse, so you should be able to copy and modify any of its content to hepl you write your book.",
	"chapters": [
		{
			"id": "introduction",
			"title": "Introduction",
			"image": "|chapter1.jpg|A photo of Boomy|Let's dive in!|Amy J. Ko|"
		},
		{
			"id": "errors",
			"title": "Errors",
			"contributors": ["Boomy", "[VS Code|https://code.visualstudio.com]"],
			"image": "|unknown.jpg|A photo of skeptical Boomy|Time to learn about errors, huh?|Amy J. Ko|"
		}
	],
	"revisions": [
		["August 30th, 2020", "Created the initial draft."]
	],
	"license": "[Creative Commons Attribution-NoDeriviatives 4.0|https://creativecommons.org/licenses/by-nd/4.0/]",
	"sources": {
		"ICER": "ACM International Computing Education Research Conference (ICER)"
	},
	"references": {
		"ref1": "Amanda Swearngin, Chenglong Wang, Alannah Oleson, James Fogarty, Amy J. Ko (2020). [Scout: Rapid Exploration of Interface Layout Alternatives through High-Level Design Constraints|http://faculty.washington.edu/ajko/papers/Swearngin2020Scout.pdf]. _ACM SIGCHI Conference on Human Factors in Computing Systems_ (CHI), 1-13.",
		"ref2": "Thomas D. LaToza, Maryam Arab, Dastyni Loksa, Amy J. Ko (2020). [Explicit Programming Strategies|http://faculty.washington.edu/ajko/papers/Latoza2020ExplicitProgrammingStrategies.pdf]. Empirical Software Engineering.",
		"ref3": [
			"Yim Register, Amy J. Ko", 2020,
			"Learning machine learning with personal data helps stakeholders ground advocacy arguments in model mechanics",
			"#ICER", 
			"http://faculty.washington.edu/ajko/papers/Register2020PersonalData.pdf"
		]
	}
}
